import { Activity, Service } from './types';

export const INITIAL_SERVICES: Service[] = [
  { name: 'Service Jeunesse Centre', code: 'centre2024' },
  { name: 'MJC Rive Gauche', code: 'mjcrivegauche' },
  { name: 'Espace Jeunes Ouest', code: 'ouest24' },
  { name: 'Maison de Quartier Est', code: 'estquartier' },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 1,
    title: 'Atelier Graffiti & Art de Rue',
    description: 'Exprime ta créativité sur de grands panneaux avec des bombes de peinture et des pochoirs. Un artiste local vous guidera.',
    date: '2024-07-15',
    startTime: '14:00',
    endTime: '17:00',
    spots: 15,
    ageRestriction: 'Plus de 12 ans',
    registrations: [
      { id: 101, firstName: 'Léo', lastName: 'Martin', youthAge: '15', department: 'Service Jeunesse Centre', comment: 'Allergie aux arachides.' },
      { id: 102, firstName: 'Clara', lastName: 'Dubois', youthAge: '16', department: 'MJC Rive Gauche' },
      { id: 103, firstName: 'Adam', lastName: 'Bernard', youthAge: '14', department: 'Service Jeunesse Centre' },
    ],
    serviceAllocations: [],
  },
  {
    id: 10,
    title: 'Tournoi de Basket 3x3',
    description: 'Rassemble ton équipe et viens montrer tes talents sur le terrain. Ambiance garantie !',
    date: '2024-07-16',
    startTime: '13:00',
    endTime: '18:00',
    spots: 24,
    registrations: [],
    serviceAllocations: [],
  },
  {
    id: 11,
    title: 'Atelier DJing',
    description: 'Apprends les bases du mixage et crée tes propres sons avec un DJ professionnel.',
    date: '2024-07-17',
    startTime: '16:00',
    endTime: '19:00',
    spots: 8,
    registrations: [],
    serviceAllocations: [],
  },
   {
    id: 12,
    title: 'Soirée Cinéma en plein air',
    description: 'Projection d\'un film culte sous les étoiles. Apporte ta couverture et ton pop-corn !',
    date: '2024-07-18',
    startTime: '21:00',
    endTime: '23:00',
    spots: 30,
    registrations: [],
    serviceAllocations: [
        { serviceName: 'Service Jeunesse Centre', spots: 15 },
        { serviceName: 'Maison de Quartier Est', spots: 15 },
    ],
  },
  {
    id: 13,
    title: 'Randonnée et Pique-nique',
    description: 'Découverte des sentiers locaux suivie d\'un grand pique-nique convivial.',
    date: '2024-07-19',
    startTime: '10:00',
    endTime: '16:00',
    spots: 20,
    registrations: [],
    serviceAllocations: [
        { serviceName: 'MJC Rive Gauche', spots: 10 },
        { serviceName: 'Espace Jeunes Ouest', spots: 10 },
    ],
  },
   {
    id: 14,
    title: 'Journée Portes Ouvertes & Barbecue',
    description: 'Viens découvrir les locaux, rencontrer les animateurs et partager un bon moment autour d\'un barbecue.',
    date: '2024-07-20',
    startTime: '12:00',
    endTime: '17:00',
    spots: 50,
    registrations: [],
    serviceAllocations: [],
  },
  {
    id: 2,
    title: 'Tournoi de Jeux Vidéo Rétro',
    description: 'Compétition amicale sur des consoles classiques. Qui sera le champion de Mario Kart 64 ?',
    date: '2024-07-22',
    startTime: '15:00',
    endTime: '18:30',
    spots: 20,
    registrations: [
        { id: 201, firstName: 'Sofiane', lastName: 'Durand', youthAge: '17', department: 'Espace Jeunes Ouest' }
    ],
    serviceAllocations: [],
  },
  {
    id: 3,
    title: 'Sortie Kayak sur la Rivière',
    description: 'Une journée rafraîchissante sur l\'eau. Apprenez les bases du kayak et profitez de la nature.',
    date: '2024-07-29',
    startTime: '09:00',
    endTime: '16:00',
    spots: 12,
    ageRestriction: 'Savoir nager obligatoire',
    registrations: [],
    serviceAllocations: [],
  },
  {
    id: 4,
    title: 'Cours de Cuisine du Monde',
    description: 'Découvrez et préparez des plats savoureux venus d\'ailleurs. Dégustation à la fin !',
    date: '2024-08-05',
    startTime: '10:00',
    endTime: '13:00',
    spots: 10,
    registrations: Array.from({ length: 10 }, (_, i) => ({
      id: 401 + i,
      firstName: 'Jeune',
      lastName: `Gourmand ${i + 1}`,
      youthAge: '16',
      department: 'Maison de Quartier Est',
    })),
    serviceAllocations: [],
  },
  {
    id: 15,
    title: 'Stage Vidéo "Crée ton court-métrage"',
    description: 'Apprends les techniques de tournage, de montage et de réalisation pour créer ton propre film en 4 jours.',
    date: '2024-08-12',
    endDate: '2024-08-15',
    startTime: '10:00',
    endTime: '16:00',
    spots: 12,
    ageRestriction: '14-17 ans',
    registrations: [],
    serviceAllocations: [],
  },
];